// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dpnm/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetCbdcRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetCbdcRequest) Reset()         { *m = QueryGetCbdcRequest{} }
func (m *QueryGetCbdcRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCbdcRequest) ProtoMessage()    {}
func (*QueryGetCbdcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b5c988d412c3d4f, []int{0}
}
func (m *QueryGetCbdcRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCbdcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCbdcRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCbdcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCbdcRequest.Merge(m, src)
}
func (m *QueryGetCbdcRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCbdcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCbdcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCbdcRequest proto.InternalMessageInfo

func (m *QueryGetCbdcRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryGetCbdcResponse struct {
	Cbdc *Cbdc `protobuf:"bytes,1,opt,name=Cbdc,proto3" json:"Cbdc,omitempty"`
}

func (m *QueryGetCbdcResponse) Reset()         { *m = QueryGetCbdcResponse{} }
func (m *QueryGetCbdcResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCbdcResponse) ProtoMessage()    {}
func (*QueryGetCbdcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b5c988d412c3d4f, []int{1}
}
func (m *QueryGetCbdcResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCbdcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCbdcResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCbdcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCbdcResponse.Merge(m, src)
}
func (m *QueryGetCbdcResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCbdcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCbdcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCbdcResponse proto.InternalMessageInfo

func (m *QueryGetCbdcResponse) GetCbdc() *Cbdc {
	if m != nil {
		return m.Cbdc
	}
	return nil
}

type QueryAllCbdcRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCbdcRequest) Reset()         { *m = QueryAllCbdcRequest{} }
func (m *QueryAllCbdcRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCbdcRequest) ProtoMessage()    {}
func (*QueryAllCbdcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b5c988d412c3d4f, []int{2}
}
func (m *QueryAllCbdcRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCbdcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCbdcRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCbdcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCbdcRequest.Merge(m, src)
}
func (m *QueryAllCbdcRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCbdcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCbdcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCbdcRequest proto.InternalMessageInfo

func (m *QueryAllCbdcRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllCbdcResponse struct {
	Cbdc       []*Cbdc             `protobuf:"bytes,1,rep,name=Cbdc,proto3" json:"Cbdc,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCbdcResponse) Reset()         { *m = QueryAllCbdcResponse{} }
func (m *QueryAllCbdcResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCbdcResponse) ProtoMessage()    {}
func (*QueryAllCbdcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b5c988d412c3d4f, []int{3}
}
func (m *QueryAllCbdcResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCbdcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCbdcResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCbdcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCbdcResponse.Merge(m, src)
}
func (m *QueryAllCbdcResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCbdcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCbdcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCbdcResponse proto.InternalMessageInfo

func (m *QueryAllCbdcResponse) GetCbdc() []*Cbdc {
	if m != nil {
		return m.Cbdc
	}
	return nil
}

func (m *QueryAllCbdcResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetCbdcRequest)(nil), "simsim.dpnm.dpnm.QueryGetCbdcRequest")
	proto.RegisterType((*QueryGetCbdcResponse)(nil), "simsim.dpnm.dpnm.QueryGetCbdcResponse")
	proto.RegisterType((*QueryAllCbdcRequest)(nil), "simsim.dpnm.dpnm.QueryAllCbdcRequest")
	proto.RegisterType((*QueryAllCbdcResponse)(nil), "simsim.dpnm.dpnm.QueryAllCbdcResponse")
}

func init() { proto.RegisterFile("dpnm/query.proto", fileDescriptor_4b5c988d412c3d4f) }

var fileDescriptor_4b5c988d412c3d4f = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x3f, 0x4b, 0xfb, 0x40,
	0x18, 0xc7, 0x9b, 0xfc, 0xfe, 0x88, 0x27, 0x68, 0x39, 0xa5, 0x94, 0xaa, 0x41, 0x52, 0x5a, 0xa5,
	0xc3, 0x1d, 0xad, 0xb3, 0x43, 0x2b, 0xd8, 0x55, 0x3b, 0x0a, 0x0e, 0x97, 0xe4, 0x88, 0x07, 0x49,
	0x2e, 0xed, 0x5d, 0xa5, 0x55, 0x5c, 0x5c, 0x5d, 0x04, 0xdf, 0x94, 0x63, 0xc1, 0xc5, 0x51, 0x5a,
	0xdf, 0x86, 0x20, 0xb9, 0x0b, 0xb5, 0xe9, 0x1f, 0xba, 0x24, 0x24, 0xf9, 0x3e, 0xf7, 0xf9, 0x3c,
	0xcf, 0x13, 0x90, 0xf7, 0xe2, 0x28, 0xc4, 0xdd, 0x3e, 0xed, 0x0d, 0x51, 0xdc, 0xe3, 0x92, 0xc3,
	0xbc, 0x60, 0xa1, 0x60, 0x21, 0x4a, 0x3e, 0xa8, 0x4b, 0xe9, 0xc0, 0xe7, 0xdc, 0x0f, 0x28, 0x26,
	0x31, 0xc3, 0x24, 0x8a, 0xb8, 0x24, 0x92, 0xf1, 0x48, 0xe8, 0x7c, 0xa9, 0xe6, 0x72, 0x11, 0x72,
	0x81, 0x1d, 0x22, 0xa8, 0x3e, 0x08, 0xdf, 0xd5, 0x1d, 0x2a, 0x49, 0x1d, 0xc7, 0xc4, 0x67, 0x91,
	0x0a, 0xa7, 0xd9, 0x1d, 0x45, 0x73, 0x1d, 0xcf, 0xd5, 0x2f, 0xec, 0x0a, 0xd8, 0xbd, 0x4a, 0x4a,
	0xda, 0x54, 0x9e, 0x3b, 0x9e, 0xdb, 0xa1, 0xdd, 0x3e, 0x15, 0x12, 0x6e, 0x03, 0x93, 0x79, 0x45,
	0xe3, 0xc8, 0x38, 0xd9, 0xec, 0x98, 0xcc, 0xb3, 0x5b, 0x60, 0x2f, 0x1b, 0x13, 0x31, 0x8f, 0x04,
	0x85, 0x35, 0xf0, 0x37, 0x79, 0x56, 0xc9, 0xad, 0x46, 0x01, 0xcd, 0xab, 0x23, 0x95, 0x56, 0x19,
	0xfb, 0x26, 0x45, 0x35, 0x83, 0x60, 0x16, 0x75, 0x01, 0xc0, 0xaf, 0x66, 0x7a, 0x50, 0x15, 0xe9,
	0x9e, 0x50, 0xd2, 0x13, 0xd2, 0xc3, 0x49, 0x7b, 0x42, 0x97, 0xc4, 0xa7, 0x69, 0x6d, 0x67, 0xa6,
	0xd2, 0x7e, 0x36, 0x52, 0xc7, 0xe9, 0xf9, 0x0b, 0x8e, 0x7f, 0xd6, 0x39, 0xc2, 0x76, 0x46, 0xc6,
	0x54, 0x32, 0xc7, 0x6b, 0x65, 0x34, 0x68, 0xd6, 0xa6, 0xf1, 0x6d, 0x80, 0x7f, 0xca, 0x06, 0xde,
	0x6b, 0x3c, 0xac, 0x2c, 0x82, 0x97, 0x4c, 0xbe, 0x54, 0x5d, 0x17, 0xd3, 0x30, 0xbb, 0xfc, 0xf4,
	0xfe, 0xf5, 0x6a, 0x1e, 0xc2, 0x7d, 0xac, 0xf3, 0x58, 0x6d, 0x76, 0xba, 0x5e, 0xfc, 0xc0, 0xbc,
	0x47, 0x38, 0x00, 0x1b, 0x49, 0x51, 0x33, 0x08, 0x56, 0xe2, 0xb3, 0xdb, 0x58, 0x89, 0x9f, 0x1b,
	0xaa, 0x6d, 0x29, 0x7c, 0x11, 0x16, 0x96, 0xe3, 0x5b, 0x67, 0x6f, 0x63, 0xcb, 0x18, 0x8d, 0x2d,
	0xe3, 0x73, 0x6c, 0x19, 0x2f, 0x13, 0x2b, 0x37, 0x9a, 0x58, 0xb9, 0x8f, 0x89, 0x95, 0xbb, 0x2e,
	0xfb, 0x4c, 0xde, 0xf6, 0x1d, 0xe4, 0xf2, 0x30, 0x53, 0x3b, 0xd0, 0x37, 0x39, 0x8c, 0xa9, 0x70,
	0xfe, 0xab, 0xbf, 0xf3, 0xf4, 0x27, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xd7, 0xa1, 0x0b, 0x1e, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// this line is used by starport scaffolding # 2
	Cbdc(ctx context.Context, in *QueryGetCbdcRequest, opts ...grpc.CallOption) (*QueryGetCbdcResponse, error)
	CbdcAll(ctx context.Context, in *QueryAllCbdcRequest, opts ...grpc.CallOption) (*QueryAllCbdcResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Cbdc(ctx context.Context, in *QueryGetCbdcRequest, opts ...grpc.CallOption) (*QueryGetCbdcResponse, error) {
	out := new(QueryGetCbdcResponse)
	err := c.cc.Invoke(ctx, "/simsim.dpnm.dpnm.Query/Cbdc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CbdcAll(ctx context.Context, in *QueryAllCbdcRequest, opts ...grpc.CallOption) (*QueryAllCbdcResponse, error) {
	out := new(QueryAllCbdcResponse)
	err := c.cc.Invoke(ctx, "/simsim.dpnm.dpnm.Query/CbdcAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// this line is used by starport scaffolding # 2
	Cbdc(context.Context, *QueryGetCbdcRequest) (*QueryGetCbdcResponse, error)
	CbdcAll(context.Context, *QueryAllCbdcRequest) (*QueryAllCbdcResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Cbdc(ctx context.Context, req *QueryGetCbdcRequest) (*QueryGetCbdcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cbdc not implemented")
}
func (*UnimplementedQueryServer) CbdcAll(ctx context.Context, req *QueryAllCbdcRequest) (*QueryAllCbdcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CbdcAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Cbdc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCbdcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Cbdc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simsim.dpnm.dpnm.Query/Cbdc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Cbdc(ctx, req.(*QueryGetCbdcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CbdcAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCbdcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CbdcAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simsim.dpnm.dpnm.Query/CbdcAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CbdcAll(ctx, req.(*QueryAllCbdcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "simsim.dpnm.dpnm.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cbdc",
			Handler:    _Query_Cbdc_Handler,
		},
		{
			MethodName: "CbdcAll",
			Handler:    _Query_CbdcAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dpnm/query.proto",
}

func (m *QueryGetCbdcRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCbdcRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCbdcRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCbdcResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCbdcResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCbdcResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Cbdc != nil {
		{
			size, err := m.Cbdc.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCbdcRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCbdcRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCbdcRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCbdcResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCbdcResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCbdcResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Cbdc) > 0 {
		for iNdEx := len(m.Cbdc) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Cbdc[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetCbdcRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCbdcResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Cbdc != nil {
		l = m.Cbdc.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCbdcRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCbdcResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Cbdc) > 0 {
		for _, e := range m.Cbdc {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetCbdcRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCbdcRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCbdcRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCbdcResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCbdcResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCbdcResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cbdc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Cbdc == nil {
				m.Cbdc = &Cbdc{}
			}
			if err := m.Cbdc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCbdcRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCbdcRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCbdcRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCbdcResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCbdcResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCbdcResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cbdc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cbdc = append(m.Cbdc, &Cbdc{})
			if err := m.Cbdc[len(m.Cbdc)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
